name: Main branch

on:
  push:
    branches:
      - "main"
    paths-ignore:
        - '.envrc'
        - '.gitignore'
        - README.*
        - LICENSE
  pull_request:
    paths-ignore:
        - '.envrc'
        - '.gitignore'
        - README.*
        - LICENSE
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# Stop previous jobs if they are still running.
# https://docs.github.com/en/actions/learn-github-actions/expressions
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Prepare Localisation, Test, Lint
    runs-on: ubuntu-latest
    
    steps:

    - name: Run CI 
      uses: bonfire-networks/bonfire-extension-ci-action@latest
      with:
        tx-token: ${{ secrets.TX_TOKEN || vars.TX_TOKEN }}
